version: '3'

services:
  db:
    image: "postgres:alpine"
    restart: always
    container_name: bl_db
    ports:
      - "5432:5432"
    env_file:
      - .deploy/db/db.env
    volumes:
      - .deploy/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: bl_backend
    hostname: api.lmanager.test
    build:
      context: .
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .deploy/apache/backend.env
    command: /usr/bin/composer test