name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
    #  - master

    # Publish `v1.2.3` tags as releases.
    #tags:
     # - v*

  # Run tests for any PRs.
  # pull_request:

env:
  IMAGE_NAME: lmanager

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: docker-compose --file docker-compose.gitlab.yml up --exit-code-from backend