name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test

    env:
      DB_HOST: postgres
      DB_NAME: lmanager_test
      DB_PORT: ${{ job.services.postgres.ports['5432'] }}
      DB_USER: bl_admin
      DB_PASS: test