name: PHP Composer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker build
        run: docker build .

    env:
      DB_HOST: db
      DB_NAME: lmanager_test
      DB_PORT: 5432
      DB_USER: bl_admin
      DB_PASS: test

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test

    env:
      DB_HOST: db
      DB_NAME: lmanager_test
      DB_PORT: 5432
      DB_USER: bl_admin
      DB_PASS: test